server:
  port: 8009
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
spring:
  application:
    name: array-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout:  120000
  ConnectTimeout: 120000

constant:
  base-url: "http://39.106.97.180:8180"
  pic-file-resource-path: "/usr/proj/file"
