export default {
  state: {
    curList: [
      {
        id: "1",
        name: "计算机组成与设计",
        time: "2019-2020",
        grade: "2018级",
        teacher: "赵小刚",
        description: "计组",
      },
      {
        id: "2",
        name: "数据结构",
        time: "2019-2020",
        grade: "2018级",
        teacher: "喻丹丹",
        description: "数据结构",
      },
      {
        id: "3",
        name: "面向对象程序设计",
        time: "2019-2020",
        grade: "2018级",
        teacher: "林馥",
        description: "JAVA",
      },
      {
        id: "4",
        name: "概率论与数理统计",
        time: "2019-2020",
        grade: "2018级",
        teacher: "钟六一",
        description: "概率论",
      },
      {
        id: "5",
        name: "大学英语3",
        time: "2019-2020",
        grade: "2018级",
        teacher: "喻士贵",
        description: "大英",
      },
    ],
    endList: [
      {
        id: "11",
        name: "数字逻辑与数字电路",
        teacher: "涂卫平",
        grade: "2018级",
        time: "2019-2020",
        description: "数字电路",
      },
      {
        id: "12",
        name: "离散数学",
        teacher: "吴志健",
        grade: "2018级",
        time: "2019-2020",
        description: "离散数学",
      },
      {
        id: "13",
        name: "高等数学B2",
        teacher: "刘伟安",
        grade: "2018级",
        time: "2019-2020",
        description: "高数",
      },
      {
        id: "14",
        name: "线性代数B",
        teacher: "黄学英",
        grade: "2019级",
        time: "2019-2020",
        description: "线代",
      },
      {
        id: "15",
        name: "面向对象程序设计",
        teacher: "桂浩",
        grade: "2019级",
        time: "2019-2020",
        description: "JAVA",
      },
    ],
    addList: [
      {
        id: "16",
        name: "数字逻辑与数字电路",
        teacher: "涂卫平",
        grade: "2018级",
        time: "2019-2020",
        description: "数字电路",
        isSelected: false,
      },
      {
        id: "17",
        name: "离散数学",
        teacher: "吴志健",
        grade: "2018级",
        time: "2019-2020",
        description: "离散数学",
        isSelected: true,
      },
      {
        id: "18",
        name: "高等数学B2",
        teacher: "刘伟安",
        grade: "2018级",
        time: "2019-2020",
        description: "高数",
        isSelected: false,
      },
      {
        id: "19",
        name: "线性代数B",
        teacher: "黄学英",
        grade: "2019级",
        time: "2019-2020",
        description: "线代",
        isSelected: false,
      },
      {
        id: "20",
        name: "面向对象程序设计",
        teacher: "桂浩",
        grade: "2019级",
        time: "2019-2020",
        description: "JAVA",
        isSelected: false,
      },
    ],
  },
  mutations: {

  },
  actions: {

  },
}